### ISSUE TITLE
API - summary contains unnecessary brackets

### ISSUE THREAD

**Issue by clytaemnestra** [pyvec/pyvo.cz#161]
When I call `https://pyvo.cz/api/series/praha-pyvo.ics` it returns me series of events in ics format. When I iterate through events and want to get the summary of a specific one, it contains brackets, which break further formatting. 

Current state:
VEVENT({'CATEGORIES': <icalendar.prop.vCategory object at 0x7fa27a9c2740>, 'DTSTART': <icalendar.prop.vDDDTypes object at 0x7fa27a9c2830>, 'SUMMARY': vText('b'(Pra\xc5\xbesk\xc3\xa9 Pyvo \xe2\x80\x93 nepotvrzeno\\; tradi\xc4\x8dn\xc3\xad term\xc3\xadn srazu)''), 'UID': vText('b'praha-pyvo-2022-10-19@pyvo.cz'')})

Desired state: 
VEVENT({'CATEGORIES': <icalendar.prop.vCategory object at 0x7fa27a9c2740>, 'DTSTART': <icalendar.prop.vDDDTypes object at 0x7fa27a9c2830>, 'SUMMARY': vText('b'Pra\xc5\xbesk\xc3\xa9 Pyvo \xe2\x80\x93 nepotvrzeno\\; tradi\xc4\x8dn\xc3\xad term\xc3\xadn srazu''), 'UID': vText('b'praha-pyvo-2022-10-19@pyvo.cz'')})

**Comment by encukou** [comment]
This is only done for meetups that are not planned yet (`nepotvrzeno; tradicni termin srazu'`).
It's intentional: the initial parenthesis is visible on small screens e.g. in Google Calendar, so you can see if the meetup is planned or if it's just a placeholder:
![image](https://user-images.githubusercontent.com/302922/194273725-000ee826-da42-4a6b-bb26-d9c37d07434d.png)
This is a description for humans, so it can change in the future. Don't parse it. If you want structured information, it would be better to add a JSON API, or add more fields to the `.ics` (if that's possible).

**Comment by clytaemnestra** [comment]
Thanks for the info! I thought it was a bug, same as @honzajavorek. In that case everything is fine.

**Comment by honzajavorek** [comment]
From the examples discussed, I thought the text contains a stringified Python tuple. The parentheses themselves are ok and I remember they're there for the planned but not confirmed meetups.
